### ISSUE TITLE
Prevent ts file from exiting

### ISSUE THREAD

**Issue by siguse** [erhise/offline-blitz#5]
Find some clever way to make the ts file keep running after the developer written code is finished, so that it can be run again on changes to the file. Ideally this should be handled outside of the file the developer is currently editing and be applied wrapping the code being tested by the developer.

**Comment by erhise** [comment]
Are your intention to have app.ts clean and use app.template to fill code?

**Comment by siguse** [comment]
I mean that it should not be needed to write code in the actual ts file to
prevent the program from exiting. ATM I'm not sure how to best achieve that
though.

Den ons 24 feb. 2021 18:06erhise <notifications@github.com> skrev:
